### PR TITLE
Feature - Components Reference Data

### PR DESCRIPTION
**Pull request by RossMurr4y**
## Description

Implements the MVP of a new page for components reference data. This data is sourced directly from the JSONSchema document (currently under development) and formats it into human-readable table(s) that define the possible component structure.

## Target Audience

- [x] hamlet users
- [ ] hamlet framework developers (incl. plugins)

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [x] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [ ] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [ ] I have added appropriate labels to this PR.
- [ ] I have added this to the `hamlet roadmap` project.

### CODE REVIEW

**Comment by RossMurr4y** [comment]
Might as well finish this off entirely before merging now. Marked as WIP for now. Can't swap back to draft though.

**Comment by ml019** [comment]
@RossMurr4y are you still tinkering or do you want it reverted from draft to review?

**Comment by RossMurr4y** [comment]
@ml019 I am still tinkering but there is one major thing I want to finish before I'd say that the MVP is complete and that is the codeblock for each component showing the possible structure of the Component. Currently its just displaying some preformated example text, but I want to have it generate from the schema. Once that's in I'll update this to 'Ready For Review' so that this can be merged.

I will prioritise that this week.

**Comment by RossMurr4y** [comment]
@roleyfoley @ml019 MVP of the references should be good to review. Could use some prettying up/applying a colour scheme but I don't want that to hold up its implementation.

[Preview here.](https://hamlet-docs-anagtif69.now.sh/)

**Pull request merged**
